### ISSUE TITLE
Can we move this repository to the cake-contrib organisation

### ISSUE THREAD

**Issue by gep13** [RadioSystems/Cake.CsvHelper#13]
@davidangel @phillipsj @DanielOliver I wanted to reach out one more time regarding moving this repository into the Cake-Contrib Organisation.

We were already able to move the Cake.AzureStorage repository into the Cake-Contrib Organisation:

https://github.com/cake-contrib/Cake.AzureStorage

And it would be great if we could move the remaining repositories, so that they can continue to be updated.

Is this something that would be possible?

If not, my intention was to fork the repository into the Organisation, to allow it to be updated, and to get a new version pushed out.  I would really rather not do this, as I feel that this dilutes the addin eco-system, and leaves it unclear about which repository is the actual source of truth.

Please let me know if you have any questions about this.

**Comment by augustoproiete** [comment]
@gep13 as you know, this addin is now maintained on https://github.com/cake-contrib/Cake.CsvHelper and this can be closed
